project:
  type: website
  output-dir: docs # command to allow publishing using docs (https://quarto.org/docs/publishing/github-pages.html)

website:

  title: "Animal-Tracking in Biologia della Conservazione — 2023/2024"
  reader-mode: true
  page-navigation: true
  description: ""
  favicon: "./figures/avatar.jpg"
  site-url: https://giulianocolosimo.github.io/animal_tracking_23_24/
  #repo-url: https://github.com/quarto-dev/quarto-demo
  repo-actions: [issue]
  open-graph:
    locale: en_US
  
  navbar:
    search: true
    right:
      - text: "Home"
        href: index.qmd
      - text: "Contacts"
        href: contacts.qmd  

  sidebar:
    logo: "./figures/avatar.jpg"
    pinned: false
    align: center
    style: "docked"
    background: light
    collapse-level: 2
    contents: 
       - href: ./classes/1/class_1.html
         text: "Class 1 - Introduction" # introduction to animal mmovement and tagging system
                                        # and setting up computer with R - RStudio and Packages
       - href: ./classes/2/class_2.html
         text: "Class 2"                # 
       - href: ./classes/3/class_3.html
         text: "Class 3"
       - href: ./classes/4/class_4.html
         text: "Class 4"
#       - href: ./classes/5/class_5.html
#         text: "Class 5"
#       - href: ./classes/6/class_6.html
#         text: "Class 6"
#       - href: ./classes/7/class_7.html
#         text: "Class 7"
#       - href: ./classes/8/class_8.html
#         text: "Class 8"


    tools:
      - icon: envelope
        url: "mailto:giuliano.colosimo@uniroma2.it"

  page-footer:
    left: "© Copyright 2023 Giuliano Colosimo"
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/). Inspiration for this site comes from [here](https://www.mm218.dev)"
    background: dark
    

format:
  html:
    #theme: [sandstone, _variables.scss]
    theme:
      light: [cosmo, theme.scss]
      dark: [cosmo, theme-dark.scss]
    mainfont: "Atkinson Hyperlegible"
    code-copy: true
    code-overflow: wrap
    toc: true
